Wifi 7305
Telecominfraproject/wlan-testing pull request #468
Opened 2022-04-18 13:09 UTC by Jyothsna-setti

Added channels for 20,40,80mhz of country GB(IOS)
Github result links:

https://github.com/Telecominfraproject/wlan-testing/actions/runs/2143856543          
https://github.com/Telecominfraproject/wlan-testing/actions/runs/2143584794         
https://github.com/Telecominfraproject/wlan-testing/actions/runs/2143583450

2022-04-18 16:12 UTC, SushantBawiskar requested changes
- Remove Interop_uc_sanity marker from channel testcases
- Remove channel code from test general security modes
- Move country code channel division dir under interOp/

2022-04-21 16:47 UTC, haricharan-jaka commented on tests/e2e/basic/validation_of_operating_modes/bridge_mode/client_connectivity/test_general_security_modes.py
> +    @pytest.mark.hari
Remove this marker

2022-04-21 16:56 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.firstrun
Remove these type of markers
```suggestion
    
```

2022-04-21 16:59 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +               pytest.mark.interop_uc_sanity, pytest.mark.bridge]
Change the marker expressions to the suggestions given below
```suggestion
pytestmark = [pytest.mark.interop, pytest.mark.ios, pytest.mark.interop_ios, pytest.mark.interop_country_code_GB,
                pytest.mark.bridge]
```

2022-04-21 17:03 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
Don't comment these lines and remove the marker in them
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code")
@allure.feature("BRIDGE MODE CLIENT CONNECT WITH COUNTRY CODE")
```

2022-04-21 17:05 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
Don't comment these lines and remove the marker in them
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT WITH COUNTRY CODE")
```

2022-04-21 17:06 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.firstrun
Remove this marker
```suggestion

```

2022-04-21 17:06 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.secondrun
Remove this marker
```suggestion

```

2022-04-21 17:07 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.secondrun
Remove this marker
```suggestion

```

2022-04-21 17:08 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT")
```

2022-04-21 17:08 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.secondrun
```suggestion

```

2022-04-21 17:08 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.secondrun
```suggestion

```

2022-04-21 17:09 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT")
```

2022-04-21 17:10 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.secondrun
```suggestion

```

2022-04-21 17:10 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.secondrun
```suggestion

```

2022-04-21 17:11 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT")
```

2022-04-21 17:12 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.thirdrun
```suggestion

```

2022-04-21 17:12 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.thirdrun
```suggestion

```

2022-04-21 17:13 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.thirdrun
```suggestion

```

2022-04-21 17:14 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT")
```

2022-04-21 17:14 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.thirdrun
```suggestion

```

2022-04-21 17:15 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT")
```

2022-04-21 17:16 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.firstrun
Remove these type of markers
```suggestion

```

2022-04-21 17:19 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.thirdrun
```suggestion

```

2022-04-21 17:19 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.thirdrun
```suggestion

```

2022-04-21 17:20 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT WITH COUNTRY CODE")
```

2022-04-21 17:20 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.thirdrun
```suggestion

```

2022-04-21 17:20 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.thirdrun
```suggestion

```

2022-04-21 17:21 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT WITH COUNTRY CODE")
```

2022-04-21 17:21 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.thirdrun
```suggestion

```

2022-04-21 17:22 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT WITH COUNTRY CODE")
```

2022-04-21 17:22 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.plot
```suggestion

```

2022-04-21 17:22 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.plot
```suggestion

```

2022-04-21 17:23 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT WITH COUNTRY CODE")
```

2022-04-21 17:23 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.subbu
Remove these type of markers
```suggestion

```

2022-04-21 17:23 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT WITH COUNTRY CODE")
```

2022-04-21 17:24 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.subbu
```suggestion

```

2022-04-21 17:24 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT WITH COUNTRY CODE")
```

2022-04-21 17:24 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.subbu
```suggestion

```

2022-04-21 17:25 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT WITH COUNTRY CODE")
```

2022-04-21 17:25 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +    @pytest.mark.subbu
```suggestion

```

2022-04-21 17:25 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT WITH COUNTRY CODE")
```

2022-04-21 17:26 UTC, haricharan-jaka commented on tests/e2e/interOp/validation_of_operating_modes/bridge_mode/country_code_channel_division/country_code_GB/iOS/test_20mhz.py
> +# @allure.feature("BRIDGE MODE CLIENT CONNECT")
```suggestion
@allure.suite(suite_name="interop country code")
@allure.sub_suite(sub_suite_name="Bridge Mode country code (GB)")
@allure.feature("BRIDGE MODE CLIENT CONNECT WITH COUNTRY CODE")
```

2022-04-25 10:28 UTC, closed without merging